In [1]:
import pymysql
from collections import defaultdict
import pandas as pd
import numpy as np

In [3]:
#Database connection
conn = pymysql.connect(user='root', password='root', database='acb', host='localhost')

#Load the data into a Pandas DataFrame
query = "select * from event left join acb.game on acb.event.game_acbid = acb.game.game_acbid where season =2018 and journey >= 21"
df = pd.read_sql(query, conn)
frames = []
team_possession_list = []
list_games = []
#GameDF dictionary
dict_of_games = {k: v for k, v in df.groupby('game_acbid')}
for game in dict_of_games.values():
    #For each team, we store a list with the possession events associated to that team. Besides, we only store the tuple (eventid, legend) associated to each event.
    #print("Game number: " + str(game.iloc[0]['game_acbid']))
    game_id = game.iloc[0]['game_acbid']
    cursor = conn.cursor() 
    sql = "SELECT id FROM game WHERE game_acbid ='%s'"
    cursor.execute(sql % game_id)
    game_id_bueno = cursor.fetchone()[0]
    list_games.append(game_id_bueno)
    list_games.append(game_id_bueno)
    game['eventid'] = list(range(1, game.shape[0]+1))
    possessions = defaultdict(list)
    #made2, made3 and turnover. These three categories are straightforward and we just insert them into each team:
    straightforward_elements = ["made2", "made3", "turnover"]
    straightforward_events = game[game["legend"].isin(straightforward_elements)]
    for _, event in straightforward_events.iterrows():
        possessions[event['team_id']].append((event['eventid'], event['legend']))
        
    #made1. We only include events of type made1 if they are the last free shot. That is, if extra_info is 1/1, 2/2 or 3/3:
    last_free_shot_elements = ["1/1", "2/2", "3/3"]
    last_free_shot_events = game[(game["legend"] == "made1") & (game["extra_info"].isin(last_free_shot_elements))]
    for _, event in last_free_shot_events.iterrows():
        possessions[event['team_id']].append((event['eventid'], event['legend']))
        
    #reb_def. Given a defensive rebound, the possession for the opponent team ends. Therefore, given a defensive rebound associated to team $i$, we insert such event to team $j$, where $i \not = j$.
    teams = list(possessions.keys())
    defensive_rebound_events = game[game["legend"] == "reb_def"]

    for _, event in defensive_rebound_events.iterrows():
        team = event['team_id']
        opponent_team = teams[(teams.index(team) + 1) % 2]
        possessions[opponent_team].append((event['eventid'], event['legend']))
    
    #technical fouls
    and_one_events = game[game["extra_info"] == "1/1"]

    for _, event in and_one_events.iterrows():
        if event['legend'] == 'made1': #1
            possessions[event['team_id']].remove((event['eventid'], event['legend']))
        else: # The shot was missed... What do I find first? Technical foul or made2/made3?
            for i in reversed(range(event['eventid'])): 
                if game[game.eventid == i].extra_info.item() == 'technical': #2
                    break
                elif (i, 'made2') in possessions[event['team_id']]: #3
                    possessions[event['team_id']].remove((i, 'made2'))
                    break
                elif (i, 'made3') in possessions[event['team_id']]: #3
                    possessions[event['team_id']].remove((i, 'made3'))
                    break
    
    #flagrant fouls
#    flagrant_elements = ["flagrant", "disqualifying"]
#    flagrant_events = game[game["extra_info"].isin(flagrant_elements)]
#    
#    for _, foul in flagrant_events.iterrows():
#        events = game[game["eventid"] > foul["eventid"]]
#        for _, event in events.iterrows():
#            if event["extra_info"] == "2/2" and event["legend"] == "miss1":
#                break
#            elif event["extra_info"] == "2/2" and event["legend"] == "made1":
#                print(possessions[event['team_code']])
#                possessions[event['team_code']].remove((event['eventid'], 'made1'))
#                break
#    
    for i, j in possessions.items():
        team_possession_list.append([i,len(j)])
        #print(i, len(j))
    
    
    def count_within_intervals(possessions, intervals):
        cont = 0
        idx_inter = 0
        idx_pos = 0
        left, right = intervals[idx_inter]
    
        while idx_pos < len(possessions):
            pos, _ = possessions[idx_pos]
            if pos < left: # smaller than the current interval, next pos...
                idx_pos+=1
            elif pos < right: # between current interval, ok!
                cont+=1
                idx_pos+=1
            else: # greater than current interval, new interval...
                idx_inter+=1
                if idx_inter == len(intervals): # no more intervals
                    break
                left, right = intervals[idx_inter]            
        return cont
    
    substitution_elements = ['sub_in', 'sub_out']
    substitutions_events = game[game['legend'].isin(substitution_elements)]
    
    
    individual_possessions = {}
    subs = substitutions_events.groupby("actor_id")
    for name, groups in subs:
        
        team = groups.iloc[0]['team_id']
        substitutions = list(groups['eventid'])
        if len(substitutions) % 2 == 1: # sometimes the last sub_out when the game ends is not registered...
            substitutions.append(game.eventid.max()+1)
        playing = list(zip(substitutions[::2], substitutions[1::2])) # intervals per player!
        individual_possessions[name] = count_within_intervals(possessions[team], playing)
        print(name)
        print(individual_possessions[name])
    
    
    s = pd.DataFrame(list(individual_possessions.items()), columns=['actor_id', 'possessions'])
    s['game_acbid'] = game_id
    s['actor_id'] = s['actor_id'].astype(int)
    frames.append(s)

df_possessions = pd.concat(frames)
#We want to extract the game_id
query = "select id, game_acbid from game where season >=2016"
df = pd.read_sql(query, conn)
joined_df = pd.merge(df_possessions, df, on='game_acbid', how='left')
result_df = joined_df.drop('game_acbid', 1)
result_df.rename(columns={'id':'game_id'}, inplace=True)
print(result_df.head())
df_possessions_team = pd.DataFrame(team_possession_list, columns=['team_id', 'possessions'])
df_possessions_team['game_id'] = list_games
print(df_possessions_team)

ValueError: Grouper for 'game_acbid' not 1-dimensional

In [48]:
#aggregate possessions by teams & players
df_possessions = df_possessions.groupby(by=['actor_id'], as_index=False)['possessions'].sum()
print(df_possessions.head(50))
df_possessions_team = df_possessions_team.groupby(by=['team_id'], as_index=False)['possessions'].sum()
print(df_possessions_team.head(50))

    actor_id  possessions
0          1          402
1          2          344
2          3          398
3          4          603
4          5          344
5          6          359
6          7          366
7          8          498
8          9          468
9         10          403
10        11          260
11        12          294
12        14          541
13        15          372
14        16          607
15        17           11
16        18          205
17        19          363
18        20          457
19        21          243
20        22          373
21        23            7
22        24          759
23        25          693
24        27          109
25        28          416
26        29          385
27        30          572
28        31          647
29        32          539
30        33          379
31        34          545
32        35          241
33        36          468
34        37            1
35        38           37
36        39           76
37        40           23
38        41          579
39        42          109
40        43          596
41        44          368
42        45          539
43        46          498
44        47          445
45        48          643
46        49          539
47        50          509
48        51          347
49        53          514
    team_id  possessions
0       1.0         1693
1       2.0         1631
2       3.0         1627
3       4.0         1656
4       5.0         1607
5       6.0         1666
6       7.0         1681
7       8.0         1668
8       9.0         1660
9      10.0         1650
10     11.0         1718
11     12.0         1733
12     13.0         1697
13     14.0         1623
14     15.0         1669
15     16.0         1707
16     17.0         1685
17     18.0         1545

In [49]:
query = "select team_home_id, team_away_id, score_home, score_away, score_home_first, score_away_first, score_home_second, score_away_second, score_home_third, score_away_third, score_home_fourth, score_away_fourth from game where season = '2018'"
df_2018 = pd.read_sql(query, conn)

In [50]:
df_2018.shape

(209, 12)

In [51]:
df_1_off = df_2018[['team_home_id','score_home']]
df_2_off = df_2018[['team_away_id','score_away']]
df_1_off.rename(columns={'team_home_id':'team_id', 'score_home': 'puntos_favor'}, inplace=True)
df_2_off.rename(columns={'team_away_id':'team_id', 'score_away': 'puntos_favor'}, inplace=True)
df_score_off = pd.concat([df_1_off, df_2_off])

df_1_deff = df_2018[['team_home_id','score_away']]
df_2_deff = df_2018[['team_away_id','score_home']]
df_1_deff.rename(columns={'team_home_id':'team_id', 'score_away': 'puntos_contra'}, inplace=True)
df_2_deff.rename(columns={'team_away_id':'team_id', 'score_home': 'puntos_contra'}, inplace=True)
df_score_deff = pd.concat([df_1_deff, df_2_deff])

C:\Users\royro\Anaconda3\lib\site-packages\pandas\core\frame.py:3027: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

In [52]:
df_score_off = df_score_off.groupby(by=['team_id'], as_index=False)['puntos_favor'].sum()
print(df_score_off.shape)
df_score_deff = df_score_deff.groupby(by=['team_id'], as_index=False)['puntos_contra'].sum()
print(df_score_deff.shape)
df_scores = pd.merge(df_score_off, df_score_deff, on='team_id', how='left')

(18, 2)
(18, 2)

In [53]:
df_ratings = pd.merge(df_possessions_team, df_scores, on='team_id', how='left')
df_ratings.head(20)

   team_id  possessions  puntos_favor  puntos_contra
0        1         1693          2038           1805
1        2         1631          2005           1741
2        3         1627          1979           1941
3        4         1656          1894           1911
4        5         1607          1795           1856
5        6         1666          1965           1680
6        7         1681          1898           1969
7        8         1668          1825           2026
8        9         1660          1937           1866
9       10         1650          1856           1805
10      11         1718          1961           1991
11      12         1733          1950           1949
12      13         1697          1895           1974
13      14         1623          1743           1864
14      15         1669          1731           1889
15      16         1707          1778           1972
16      17         1685          1870           1930
17      18         1545          1840           1791

In [54]:
#Quiero nombres
query = "SELECT * FROM acb.team"
df_teamnames = pd.read_sql(query, conn)
df_teamnames.rename(columns={'id':'team_id'}, inplace=True)
df_ratings = pd.merge(df_ratings, df_teamnames, on='team_id', how='left')

In [55]:
df_ratings.head()

  team_id  possessions  puntos_favor  puntos_contra team_acbid  founded_year
0       1         1693          2038           1805        MAD          1931
1       2         1631          2005           1741        BAR          1926
2       3         1627          1979           1941        RON          1977
3       4         1656          1894           1911        AND          1970
4       5         1607          1795           1856        OBR          1970

In [56]:
df_ratings['off_rating'] = (df_ratings['puntos_favor'] * 100) / df_ratings['possessions']
df_ratings['deff_rating'] = (df_ratings['puntos_contra'] * 100) / df_ratings['possessions']
df_ratings['net_rating'] = df_ratings['off_rating'] - df_ratings['deff_rating']
df_ratings = df_ratings.sort_values('net_rating', ascending = False).head(20)

In [57]:
df_ratings.head(20)

,team_id,possessions,puntos_favor,puntos_contra,team_acbid,founded_year,off_rating,deff_rating,net_rating
5,6,1666,1965,1680,BAS,1959,117.947179,100.840336,17.106843
1,2,1631,2005,1741,BAR,1926,122.930717,106.744329,16.186389
0,1,1693,2038,1805,MAD,1931,120.378027,106.615475,13.762552
8,9,1660,1937,1866,CAN,1939,116.686747,112.409639,4.277108
17,18,1545,1840,1791,PAM,1986,119.093851,115.922330,3.171521
9,10,1650,1856,1805,JOV,1930,112.484848,109.393939,3.090909
2,3,1627,1979,1941,RON,1977,121.634911,119.299324,2.335587
11,12,1733,1950,1949,MAN,1931,112.521639,112.463935,0.057703
3,4,1656,1894,1911,AND,1970,114.371981,115.398551,-1.026570
10,11,1718,1961,1991,BRG,1994,114.144354,115.890570,-1.746217
16,17,1685,1870,1930,CLA,1963,110.979228,114.540059,-3.560831
4,5,1607,1795,1856,OBR,1970,111.698818,115.494711,-3.795893
6,7,1681,1898,1969,EST,1948,112.908983,117.132659,-4.223676
12,13,1697,1895,1974,ZZA,2002,111.667649,116.322923,-4.655274
13,14,1623,1743,1864,MUR,1985,107.393715,114.849045,-7.455330
14,15,1669,1731,1889,BRE,1966,103.714799,113.181546,-9.466747
15,16,1707,1778,1972,GBC,2001,104.159344,115.524312,-11.364968
7,8,1668,1825,2026,FUE,1981,109.412470,121.462830,-12.050360